mulesoft-anypoint/anypoint-automation-client-generator

.github/workflows/pipeline.yaml

Missing attributes: 
* staticIPsDisabled
* workers
* proxyReadTimeout
* clientCertLabel
* clientCert
* revocationListLabel
* revocationList 
* upstreamProtocol

adds missing attributes to DLB

---

README.md
package-lock.json
package.json
spec/dlb.yml

Missing attributes:
* staticIPsDisabled
* workers
* proxyReadTimeout
* clientCertLabel
* clientCert
* revocationListLabel
* revocationList
* upstreamProtocol

Add missing attributes to DLB resource

---

.github/workflows/pipeline.yaml
README.md
package-lock.json
package.json
spec/dlb.yml

Missing attributes:
* staticIPsDisabled
* workers
* proxyReadTimeout
* clientCertLabel
* clientCert
* revocationListLabel
* revocationList
* upstreamProtocol

Updates DLB Spec and Updates npm dependencies

---

.github/workflows/pipeline.yaml
spec/apim.yml
spec/apim_upstream.yml

Adds: 
* API Manager API
* API Manager Upstreams API
* Flex Gateway Upstream API

Api Manager and Flex Gateway

---

openapitools.json
spec/secretgroup.yml
spec/secretgroup_certificate.yml
spec/secretgroup_crl_distributor_configs.yml
spec/secretgroup_keystore.yml
spec/secretgroup_tlscontext.yml
spec/secretgroup_truststore.yml

Includes the following specs: 
* secretgroup
* secretgroup_truststore
* secretgroup_tlscontext
* secretgroup_keystore
* secretgroup_crl_distributor_configs
* secretgroup_certificate

Adds Secret Group Resources

---

spec/apim_policy.yml

Adds Specification for API Manger Policies

API Manager Policies

---

spec/connected_app.yml

* Adds missing parameters to all requests
* General enhancements

connected_app: updates paths to adds org

---

spec/connected_app.yml

Adds new route to get connected app without orgId

updates connected app spec 

---

spec/connected_app.yml

adds missing org_id attribute to responses

Connected App Module enhancements

---

spec/exchange_assets.yml

`GET` `/assets/{orgId}/{assetId}/{version}/asset`
https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-experience-api/minor/2.3/console/method/%233753/

Exchange assets get

---

spec/exchange_assets.yml

adds spec for a service to get asset by version.

Exchange Resource: Get Asset by Version

---

spec/exchange_assets.yml

Update postAssetResponse to properly handle metadata.tags as an array

Enhances Exchange Asset 

---

spec/idp.yml

updates idp spec, changes all body, path and get objects

Fix IDP Spec

---

spec/apim.yml
spec/idp.yml

Updates isCloudhub field from string to boolean which was causing issues.

Update API Manager's Interface

---

spec/exchange_apps.yml

Creates spec to handle exchange applications.
The specification mainly focuses on how to create, read and delete exchange applications.

Introduce Exchange Apps Spec

---

spec/application_manager_v2.yml

Introduces specification to handle exchange client applications.

New: Exchange Apps 

---

spec/application_manager_v1.yml
spec/exchange_client_apps.yml

Creates the  application manager v1 that uses the anypoint api armui to list all applications.

NEW: application manager v1

---

spec/application_manager_v1.yml

Adds a missing property to Deployment object

Update: application_manager_v1 

---

spec/application_manager_v1.yml

Adds a missing attribute `deploymentUpdateStatus` to the Deployment object schema.

Update: application_manager_v1

---

spec/application_manager_v1.yml

Fixes format issue with timestamp format

application_manager_v1: updates timestamp format for dates to int64

---

spec/apim.yml
spec/apim_contract.yml

* Creates new spec for handling api manager contracts: 
* contains the full CRUD operations for handling api contracts 
* adds a new resource to API Manager spec to get information about the asset linked to a given api instance.

API Manager & API Contracts

---

spec/apim_policy.yml

* Creates new spec for handling api manager contracts: 
* contains the full CRUD operations for handling api contracts 
* adds a new resource to API Manager spec to get information about the asset linked to a given api instance.

API Manager & API Manager Contracts

---

spec/org.yml

Update the org specification to: 
* Add new resource to get the usage of an organization
* Add new entitlements
* Reorganizes schemas to avoid redundancy

Org Schema Update

---

spec/org.yml

Removes empty default values for objects and arrays.

Org spec enhancement

---

spec/org.yml

fixes issue with globalDeployment entitlement in org module

Org Spec Fix

---

spec/org.yml

Adds missing Entitlements:
* managedGatewaySmall
* managedGatewayLarge
* networkConnections
* monitoringCenter: adds missing properties

Feature: Org Entitlements Enrichment

---

Makefile
spec/application_manager_v1.yml

* Added resources: 
* list ch1 deployments
* Rationalizes schemas
* Enriches existing schemas:
* IpAddresse
* LogLevels
* Workers
* MuleVersion

Feature: Adds List of CH1 deployments to Application Manager V1 

---

spec/user.yml

updates the user spec to re-organize it and adds operation ids to all resources.

Feature: User

---

spec/user.yml

Enhancing schemas & removes useless schemas.

Refactor: User spec quality enhancement

---

spec/team.yaml
spec/team_group_mappings.yaml
spec/team_members.yaml
spec/team_roles.yaml

Updates Team related spec to add operationId. Cleans schemas and resource parameters for : 
* team
* team_roles
* team_members
* team_group_mappings

Refactor: Team Related Specs

---

spec/team_group_mappings.yaml

refactors team_group_mappings to add operationId to all resources

Refactor: Team group mappings

---

.gitignore
spec/application_manager_v1.yml
spec/application_manager_v2.yml
spec/private_space.yml
spec/private_space_tlscontext.yml

Preparing releases for:
* Application Manager v1: adds the possibility to deploy an application to CH1 using artefact stored in exchange. 
* Creates new specifications:
* Private Space
* Private Space TLS Context

Merging Develop

---

spec/private_space.yml

* Updates body schemas for POST and PATCH resources
* Adds IAM role GET resource for reading private space's IAM role.

Adds IAM role + body enhancement
